### ISSUE TITLE
PSA documentation link does not work

### ISSUE THREAD

**Issue by Bai-Li-NOAA** [nmfs-fish-tools/PSA#1]
Hello @ChristineStawitz-NOAA,

I received a report that the PSA documentation link on the FIT website does not work. The error message is
`You don't have permission to access /tm/TM101.pdf on this server.`

Could we update the link or remove the link? Would the link below work?
[Use of productivity and susceptibility indices to determine stock vulnerability, with example applications to six U.S. fisheries](https://repository.library.noaa.gov/view/noaa/3713)

**Comment by ChristineStawitz-NOAA** [comment]
thanks for catching this Bai - fixed this and also a typo in the link title with commit 2a086973c177b7e9e12c2f288a3b9eb5eddb503c
